  PROCEDURE SetFlags;
    Begin
      RecyclesSet          := False;
      ARecycleSet          := False;
      BRecycleSet          := False;
      ConfigSpecified      := False;
      OperationSpecified   := False;
      SteadyDataSpecified  := False;
      DiurnalDataSpecified := False;
      SteadyStateSpecified := False;
      DiurnalSpecified     := False;
      WasteSpecified       := False;
    End;  { set flags }

